#@data/values-schema
#@ load("@ytt:data", "data")
---
service: ""
container: "us-docker.pkg.dev/joshlong/mogul-artifact-registry/bootiful-loom:latest"
vt: false
url: ""
port: 8080
probes:
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
    httpGet:
      port: 8080
      path: /actuator/health/readiness
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
    httpGet:
      port: 8080
      path: /actuator/health/liveness
