#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ str(data.values.service) + '-deployment'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ str(data.values.service)
  template:
    metadata:
      labels:
        app: #@ str(data.values.service)
    spec:
      containers:
        - name: #@ data.values.service  + '-container'


          image: #@ data.values.container
          imagePullPolicy: Always
          #@ if data.values.probes.livenessProbe :
          livenessProbe: #@ data.values.probes.livenessProbe
          #@ end
          #@ if data.values.probes.readinessProbe :
          readinessProbe: #@ data.values.probes.readinessProbe
          #@ end
          ports:
            - containerPort:  #@ data.values.port
          envFrom:
            - secretRef:
                name: devoxx-uk-2024-secrets
          env:
            - name: SERVER_PORT
              value:  #@ str(data.values.port)
            - name: LANG
              value: "en_US.UTF-8"

---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.service  + '-service'
spec:
  type: NodePort
  selector:
    app: #@ data.values.service
  ports:
    - port:  #@ data.values.port
      targetPort:  #@ data.values.port

